/**
 * The referring sources and how to reach each one.
 *
 * Kept in the repository rather than in a spreadsheet so the send path needs
 * no access to anything but this code. It is seeded into an empty recipients
 * table on first boot and never again — after that the dashboard owns it, and
 * an edit made there is not undone by a deploy.
 *
 * `channel` is how this source is reached, and it decides how the message
 * goes out: a source with a phone is a WhatsApp source, one with an address
 * is an email source. A row with neither is deliberate — the source is real
 * and busy, but nobody has an address for it, so it stays silent and visible
 * rather than looking like an oversight.
 *
 * `leads` is the volume each source carried when this list was written. It is
 * a hint for ordering the work, not something the sender reads.
 */
export const SEED_RECIPIENTS = [
  { sourceName: "אבירן שלם", whatsapp: "+972542471430", channel: "whatsapp", leads: 17 },
  { sourceName: "אג'נדה", email: "eliran@agenda-fs.com", channel: "email", leads: 13 },
  { sourceName: "אסף נתנאל (אושרי שתפ)", whatsapp: "+972528262075", channel: "whatsapp", leads: 6 },
  { sourceName: "בר יוחאי מסוכנות ביטוח (ממש להגיד ככה)", whatsapp: "+972525854583", channel: "whatsapp", leads: 2 },
  { sourceName: "גיא שטטל - סוכן (אושרי)", whatsapp: "+972558819804", channel: "whatsapp", leads: 8 },
  { sourceName: "דוד בינשטוק", whatsapp: "+972503081462", channel: "whatsapp", leads: 2 },
  { sourceName: "הילית", whatsapp: "+972525614232", channel: "whatsapp", leads: 23 },
  { sourceName: "ורד שוייגמן", whatsapp: "+972529285501", channel: "whatsapp", leads: 9 },
  { sourceName: "ורד שוייגמן - סו\"ב", whatsapp: "+972529285501", channel: "whatsapp", leads: 5 },
  { sourceName: "זוהר נוריאל  -יועצת משכנתאות", whatsapp: "+972528750487", channel: "whatsapp", leads: 3 },
  { sourceName: "מטאור - אבי אבוחצירא", email: "avi@nehorai-ins.com", channel: "email", leads: 3 },
  { sourceName: "מטאור - אביאל ואקנין", email: "aviel@one-ins.net", channel: "email", leads: 18 },
  { sourceName: "מטאור - אביב אליהו", email: "info@eliya-ins.co.il", channel: "email", leads: 7 },
  { sourceName: "מטאור - אביבה מילמן", email: "avivamilman@gmail.com", channel: "email", leads: 8 },
  { sourceName: "מטאור - אביטל פרדו", email: "avital@pardo-ins.com", channel: "email", leads: 16 },
  { sourceName: "מטאור - אביעד ממן", email: "Aviad@maman-fin.co.il", channel: "email", leads: 4 },
  { sourceName: "מטאור - אהוד מערבי", email: "ehudfinance@gmail.com", channel: "email", leads: 3 },
  { sourceName: "מטאור - אופק הוגן", email: "sherut@ofekhogen.co.il", channel: "email", leads: 31 },
  { sourceName: "מטאור - אורן ד'גנה", email: "oren@orendg-ins.com", channel: "email", leads: 7 },
  { sourceName: "מטאור - אושרי כהן", email: "oshri@cohen-ins.net", channel: "email", leads: 56 },
  { sourceName: "מטאור - אושרי כהן (אנג'ל)", email: "oshri@cohen-ins.net", channel: "email", leads: 3 },
  { sourceName: "מטאור - איגור וסרמן", email: "igorv@igor-ins.com", channel: "email", leads: 22 },
  { sourceName: "מטאור - אייל רז", email: "eyal@razmashkanta.com", channel: "email", leads: 5 },
  { sourceName: "מטאור - איתי נדב", email: "itay@nadav-ins.co.il", channel: "email", leads: 11 },
  { sourceName: "מטאור - איתי צאיג", email: "itay@prosure-ins.com", channel: "email", leads: 21 },
  { sourceName: "מטאור - אלדרוטי", email: "limor@alderoty.co.il", channel: "email", leads: 27 },
  { sourceName: "מטאור - אלי קדושים", email: "elieliko31@gmail.com", channel: "email", leads: 10 },
  { sourceName: "מטאור - אלעד מאור", email: "elad@mz-ins.co.il", channel: "email", leads: 9 },
  { sourceName: "מטאור - אלעד סבג", email: "elad@sabag-ins.co.il", channel: "email", leads: 19 },
  { sourceName: "מטאור - אסף ג'רבי", email: "asaf@gerbi-ins.co.il", channel: "email", leads: 8 },
  { sourceName: "מטאור - ארי מאמו", email: "ari@mamou-ins.co.il", channel: "email", leads: 9 },
  { sourceName: "מטאור - אריאל יואב דביר", email: "ariel@ayd-plan.com", channel: "email", leads: 250 },
  { sourceName: "מטאור - בועז אדלר", email: "boaz@adler-ins.co.il", channel: "email", leads: 17 },
  { sourceName: "מטאור - בני פישר", email: "benny@fisherfin.co.il", channel: "email", leads: 18 },
  { sourceName: "מטאור - ברק וולפלד", email: "barak@welfeld.co.il", channel: "email", leads: 15 },
  { sourceName: "מטאור - גולן זרחי", email: "golanzarhi@gmail.com", channel: "email", leads: 6 },
  { sourceName: "מטאור - גיא וולף", email: "guywolfhag@gmail.com", channel: "email", leads: 12 },
  { sourceName: "מטאור - דור כהן", email: "dor@ins-dor.co.il", channel: "email", leads: 10 },
  { sourceName: "מטאור - דור כהן (קהילה גאה)", email: "dor@ins-dor.co.il", channel: "email", leads: 2 },
  { sourceName: "מטאור - דניאל גיבלי", email: "daniel@gibali.co.il", channel: "email", leads: 14 },
  { sourceName: "מטאור - הילה זרדוק", email: "hila@zardok-ins.co.il", channel: "email", leads: 5 },
  { sourceName: "מטאור - המצפן הפיננסי (סאלי&אריאל)", email: "ayizhak@gmail.com", channel: "email", leads: 95 },
  { sourceName: "מטאור - הראל פנחס", email: "harel@pinhas-ins.co.il", channel: "email", leads: 2 },
  { sourceName: "מטאור - חיים מלול", email: "dalit@malul-ins.co.il", channel: "email", leads: 8 },
  { sourceName: "מטאור - חן גואטה", email: "hen@gueta-ins.co.il", channel: "email", leads: 2 },
  { sourceName: "מטאור - חנוך שוורץ", email: "s.chanoch@gmail.com", channel: "email", leads: 4 },
  { sourceName: "מטאור - טלי ירושלמי", email: "Tali@yerushalmi-ins.co.il", channel: "email", leads: 3 },
  { sourceName: "מטאור - יאיר חן", email: "henyair55@outlook.co.il", channel: "email", leads: 30 },
  { sourceName: "מטאור - ידידיה רפאלוב", email: "didirefaelo@gmail.com", channel: "email", leads: 2 },
  { sourceName: "מטאור - יהודה צרויה", email: "Yehuda@tzruya.biz", channel: "email", leads: 65 },
  { sourceName: "מטאור - יוסי חזוט", email: "yossi@hazut-ins.co.il", channel: "email", leads: 20 },
  { sourceName: "מטאור - יוסי רותם", email: "Yossi@rotem-ins.co.il", channel: "email", leads: 14 },
  { sourceName: "מטאור - יורם פנקר", email: "penkar2012@gmail.com", channel: "email", leads: 1 },
  { sourceName: "מטאור - ירדן גואטה", email: "yarden@raviv-ins.co.il", channel: "email", leads: 8 },
  { sourceName: "מטאור - לי דואדי", email: "lee@duadi-ins.com", channel: "email", leads: 3 },
  { sourceName: "מטאור - ליטל פרקש", email: "Lital@elf-ins.co.il", channel: "email", leads: 22 },
  { sourceName: "מטאור - מאיה בן אדרת", whatsapp: "+972544897364", channel: "whatsapp", leads: 12 },
  { sourceName: "מטאור - מאיר זילברמן", email: "meir@zilberman-ins.co.il", channel: "email", leads: 9 },
  { sourceName: "מטאור - מורג איפרגן", email: "morag@morgan-fin.com", channel: "email", leads: 4 },
  { sourceName: "מטאור - מיטל שלום", email: "meital@shalom-ins.com", channel: "email", leads: 11 },
  { sourceName: "מטאור - מיכאל בראילוב", email: "michaelbfinins@gmail.com", channel: "email", leads: 7 },
  { sourceName: "מטאור - מיקי פינטו", email: "miki@pintoins.co.il", channel: "email", leads: 5 },
  { sourceName: "מטאור - מעיין בר אור", email: "agent@maayan-insure.com", channel: "email", leads: 3 },
  { sourceName: "מטאור - מעיין חיינובסקי", email: "MAAYAN@MMH-INS.CO.IL", channel: "email", leads: 10 },
  { sourceName: "מטאור - מרינה פריצקר", email: "marina@marina-finance.com", channel: "email", leads: 10 },
  { sourceName: "מטאור - נועה מלכה", email: "noa@noa-malka.com", channel: "email", leads: 24 },
  { sourceName: "מטאור - נופר (כוכב)", email: "Nofar.suli@gmail.com", channel: "email", leads: 24 },
  { sourceName: "מטאור - נטלי איטח", email: "natali@n-i.co.il", channel: "email", leads: 1 },
  { sourceName: "מטאור - ניב מויאל", email: "nivmoyal@moyal-ins.co.il", channel: "email", leads: 24 },
  { sourceName: "מטאור - ניב ניסן", email: "niv@simple-ins.com", channel: "email", leads: 17 },
  { sourceName: "מטאור - נרקיס יפרח", email: "narkis@b-haim.co.il", channel: "email", leads: 1 },
  { sourceName: "מטאור - נתנאל יוחננוב", email: "nati@yo-ins.co.il", channel: "email", leads: 15 },
  { sourceName: "מטאור - סיון", email: "sivan0508851456@gmail.com", channel: "email", leads: 2 },
  { sourceName: "מטאור - סימה אמסלם", email: "sima@amsalem-ins.co.il", channel: "email", leads: 3 },
  { sourceName: "מטאור - סימו סבן", email: "accounting@finbot.co.il", channel: "email", leads: 4 },
  { sourceName: "מטאור - ספיר וניקיטה קומרוב", email: "sapir@komarov-ins.co.il", channel: "email", leads: 16 },
  { sourceName: "מטאור - עדי כוכב", email: "Adi@kochav.co.il", channel: "email", leads: 12 },
  { sourceName: "מטאור - עומרי מדמון", email: "omri@madmon-ins.co.il", channel: "email", leads: 1 },
  { sourceName: "מטאור - עידו אלקיים", email: "ido-noam@meteor-ins.co.il", channel: "email", leads: 2 },
  { sourceName: "מטאור - עידו כהן", email: "ido@gibali.co.il", channel: "email", leads: 4 },
  { sourceName: "מטאור - עידו כהן (כבאות 13%)", email: "ido@gibali.co.il", channel: "email", leads: 37 },
  { sourceName: "מטאור - עידן כהן", email: "idan@coh-ins.co.il", channel: "email", leads: 3 },
  { sourceName: "מטאור - עידן מלול", email: "idan@idanhadash-ins.co.il", channel: "email", leads: 4 },
  { sourceName: "מטאור - עמית טל", email: "amit@tal-ins.org", channel: "email", leads: 13 },
  { sourceName: "מטאור - ענת הרוש", email: "tushinka@gmail.com", channel: "email", leads: 4 },
  { sourceName: "מטאור - ערן מסיקה", email: "eran.mesika@gmail.com", channel: "email", leads: 4 },
  { sourceName: "מטאור - פרח סאיג", email: "farah@sayegh-ins.co.il", channel: "email", leads: 3 },
  { sourceName: "מטאור - צבי חלילוב", email: "tzvih87@gmail.com", channel: "email", leads: 9 },
  { sourceName: "מטאור - קובי בנין", email: "kobi@meteor-group.co.il", channel: "email", leads: 1 },
  { sourceName: "מטאור - רון טויטו", email: "office@rontwito.com", channel: "email", leads: 1 },
  { sourceName: "מטאור - רונן דוידוב", email: "ronen1367@gmail.com", channel: "email", leads: 11 },
  { sourceName: "מטאור - רונן קליקר", email: "noreply@ezcount.co.il", channel: "email", leads: 13 },
  { sourceName: "מטאור - רועי כץ", email: "roei@katz-fin.co.il", channel: "email", leads: 25 },
  { sourceName: "מטאור - רועי פרל", email: "notify@morning.co", channel: "email", leads: 6 },
  { sourceName: "מטאור - רועי ששון", email: "sassonins@gmail.com", channel: "email", leads: 1 },
  { sourceName: "מטאור - רפאל טבקה", email: "raphaeltebekaconsulting@gmail.com", channel: "email", leads: 3 },
  { sourceName: "מטאור - שובל זקס", email: "shoval@zaks1.co.il", channel: "email", leads: 16 },
  { sourceName: "מטאור - שחר איילון", email: "shachar@ayalonk-ins.co.il", channel: "email", leads: 9 },
  { sourceName: "מטאור - שיר לוי", email: "shirfinan@gmail.com", channel: "email", leads: 1 },
  { sourceName: "מטאור - שלום טל", email: "shalom@ts-ins.co.il", channel: "email", leads: 2 },
  { sourceName: "מטאור - שלומי שוורץ", email: "shlomy@schwartz-ins.co.il", channel: "email", leads: 2 },
  { sourceName: "מטאור - שרפליס", email: "mati@sherflis.com", channel: "email", leads: 4 },
  { sourceName: "מטאור - תומר כהן", email: "office@tomerfinance.co.il", channel: "email", leads: 2 },
  { sourceName: "משה הולצברג ניהול תיקי לקוחות", whatsapp: "+972534723928", channel: "whatsapp", leads: 8 },
  { sourceName: "נטו שכר - נטליה", email: "Office@netosachar.co.il", channel: "email", leads: 23 },
  { sourceName: "נטו שכר חלוקה 50% (נטליה)", email: "Office@netosachar.co.il", channel: "email", leads: 18 },
  { sourceName: "סו\"ב אפרים רם", email: "pyrm0520@gmail.com", channel: "email", leads: 27 },
  { sourceName: "סו\"ב ארז מלכה", whatsapp: "+972524411478", channel: "whatsapp", leads: 15 },
  { sourceName: "סו\"ב ארתור אופניק", whatsapp: "+972535936369", channel: "whatsapp", leads: 5 },
  { sourceName: "סו\"ב גל רחמני 20%", whatsapp: "+972506022230", channel: "whatsapp", leads: 5 },
  { sourceName: "סו\"ב דן יצחק", whatsapp: "+972506347480", channel: "whatsapp", leads: 3 },
  { sourceName: "סו\"ב יוסי עזריאל", whatsapp: "+972525574454", channel: "whatsapp", leads: 12 },
  { sourceName: "סו\"ב מיטל גיברלטר", whatsapp: "+972509012455", channel: "whatsapp", leads: 84 },
  { sourceName: "סו\"ב- ניסן זטלאווי", whatsapp: "+972546472464", channel: "whatsapp", leads: 27 },
  { sourceName: "סו\"ב נתנאל שמש (20%)", whatsapp: "+972502810687", channel: "whatsapp", leads: 4 },
  { sourceName: "סו\"ב סתיו אורן", whatsapp: "+972526885804", channel: "whatsapp", leads: 10 },
  { sourceName: "עו\"ד - מיכל ישראלי", whatsapp: "+972502107898", channel: "whatsapp", leads: 3 },
  { sourceName: "עו\"ד - רינה שוסטר", whatsapp: "+972545936120", channel: "whatsapp", leads: 5 },
  { sourceName: "עידן שלום - יועץ פיננסי", whatsapp: "+972528321788", channel: "whatsapp", leads: 11 },
  { sourceName: "פז טפירו", whatsapp: "+972542073666", channel: "whatsapp", leads: 9 },
  { sourceName: "פמילי ביז - סוכנים שונים (הערות)", leads: 60 },
  { sourceName: "אדל - אליפים (סו\"ב)", leads: 2 },
  { sourceName: "אופיר סלם", leads: 2 },
  { sourceName: "אוקלר - בן אמסלם", leads: 2 },
  { sourceName: "אורן רגב", leads: 2 },
  { sourceName: "דלית אוחיון - יו\"מ", leads: 10 },
  { sourceName: "ורד דוקטורי", leads: 1 },
  { sourceName: "חבר מביא חבר", leads: 291 },
  { sourceName: "טיקטוק", leads: 1 },
  { sourceName: "יעל חן (לבדוק מי זו)", leads: 1 },
  { sourceName: "ירון אלישע עו\"ד", leads: 1 },
  { sourceName: "לימור צוברי יו\"ס", leads: 1 },
  { sourceName: "לקוח עבר", leads: 86 },
  { sourceName: "לקוח קיים", leads: 40 },
  { sourceName: "מושיקו סוכן ביטוח (חיצוני)", leads: 2 },
  { sourceName: "מזדמן", leads: 49 },
  { sourceName: "מטאור - אביעד דוידי", leads: 3 },
  { sourceName: "מטאור - אורנה כהן", leads: 2 },
  { sourceName: "מטאור - אריאל & אושרי", leads: 5 },
  { sourceName: "מטאור - דניאל גודוב", leads: 4 },
  { sourceName: "מטאור - יקיר צרויא", leads: 3 },
  { sourceName: "מטאור - מור אלקיים", leads: 33 },
  { sourceName: "מטאור - סוכנות סאני", leads: 1 },
  { sourceName: "מטאור - שחר שמשון", leads: 7 },
  { sourceName: "מידרג", leads: 53 },
  { sourceName: "מיקי נעים (חבר)", leads: 2 },
  { sourceName: "משאבים - אליפים", leads: 9 },
  { sourceName: "משה טל", leads: 4 },
  { sourceName: "סו\"ב עמית בללי", leads: 3 },
  { sourceName: "עו\"ד קן דרור", leads: 1 },
  { sourceName: "עוגנים פיננסים", leads: 374 },
  { sourceName: "עמותת אנוש (משה טל)", leads: 2 },
  { sourceName: "פייסבוק", leads: 5 },
  { sourceName: "פנחס רוזמן סו\"ב", leads: 1 },
  { sourceName: "פסגות - ליאור ברק", leads: 6 },
  { sourceName: "קמפיין", leads: 485 },
  { sourceName: "רונן נגר עו\"ד", leads: 2 },
  { sourceName: "רחל מכלוף", leads: 4 },
  { sourceName: "שפע", leads: 15 },
  { sourceName: "שרי דביר עו\"ד", leads: 1 }
];
